name: Node.js CI


on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-tests:
    name: Node.js Tests on ${{ matrix.platform }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, s390x]
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v3

      - name: Setup QEMU (for s390x)
        if: matrix.platform == 's390x'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: s390x

      - name: Run Node.js tests on ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "s390x" ]; then
            echo "Running Node.js tests on s390x platform..."
            docker run --rm --platform linux/s390x \
              -v $(pwd):/app \
              -w /app \
              ubuntu:22.04 bash -c "
                export DEBIAN_FRONTEND=noninteractive
                apt-get update
                apt-get install -y wget tar xz-utils bc python3 php-cli gcc
                wget https://nodejs.org/dist/v22.15.0/node-v22.15.0-linux-s390x.tar.xz
                tar -xf node-v22.15.0-linux-s390x.tar.xz
                cp -r node-v22.15.0-linux-s390x/* /usr/local/
                echo "/usr/local/bin" >> $GITHUB_PATH
                npm install
                npm run test:e2e
                npm run test:unit
              "
          # else
          #   echo "Running Node.js tests on amd64 platform..."
          #   sudo apt install python3
          #   sudo apt install php-cli
          #   npm install
          #   npm run test:e2e
          #   npm run test:unit
          fi

  # bun-tests:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #   - name: Remove Node.js installed by setup-node action (if any)
  #     run: |
  #       if command -v node &> /dev/null; then
  #         sudo rm -rf "$(which node)"
  #       fi
  #       if command -v npm &> /dev/null; then
  #         sudo rm -rf "$(which npm)"
  #       fi

  #   - name: Setup Bun
  #     uses: oven-sh/setup-bun@v1
  #   - name: Install dependencies using Bun
  #     run: bun install
  #   - name: Run end-to-end tests with Bun
  #     run: bun run test:e2e
  #   - name: Run unit tests with Bun
  #     run: bun run test:unit
